language: python
python:
  - "3.7"

env:
  - PLATFORMIO_PROJECT_DIR=examples/arduino-blink
  - PLATFORMIO_PROJECT_DIR=examples/arduino-wifiscan
  - PLATFORMIO_PROJECT_DIR=examples/freertos-blink
  - PLATFORMIO_PROJECT_DIR=examples/native-blink

install:
  - pip install -U https://github.com/OS-Q/S03/archive/master.zip
  - platformio platform install https://github.com/OS-Q/P15.git

script:
  - platformio run -s -d $PLATFORMIO_PROJECT_DIR

notifications:
  email: false
